name: Multi Job Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Step
        run: echo "Running Tests..."

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "Building Application..."

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Step
        run: echo "Deploying Application..."