name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  run-javascript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Node Version
        run: node -v

      - name: Install Dependencies
        run: npm install
        
      - name: Run Math File
        run: node math.js